name: financial_aid_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Web Specific

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  eva_icons_flutter: ^3.1.0

  # UI & Theming
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1

  # State Management (Choose One: GetX, Riverpod, Provider, Bloc)
  get: ^4.7.1
  url_strategy: ^0.3.0
  intl: ^0.20.2
  get_storage: ^2.1.1
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/hero.png
    - assets/images/logo.svg
    - assets/images/animations/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
