name: financial_aid_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Web Specific

  # State management

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  # Icons

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ------------ Local Assets --------------- #
  #assets:

  #------------- Local Fonts ---------------- #
  #fonts:
